management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh, bus-env
server:
  port: 18080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jaredbark/spring-cloud-config-repo
    bus:
      enabled: true
  rabbitmq:
    host: 192.168.1.48
    port: 5672
    username: test
    password: test